### ISSUE TITLE
Update to react 15.0.1

### ISSUE THREAD

**Issue by doktor500** [hongymagic/react-number-input#15]
To avoid this issue https://gist.github.com/jimfb/4faa6cbfb1ef476bd105 react-number-input needs to be updated to react 15.0.1

**Comment by leojh** [comment]
It looks like it may be more than just updating to React 15.0.1. From what I'm seeing, if upgrade AND comment out any lines that reference .refs, then the warning goes away.

**Comment by leojh** [comment]
If I just import ```react-number-input.js``` into my 15.0.* app as a regular component, then it seems to work fine.

**Comment by hongymagic** [comment]
It should work without any hassle. However, I am upgrading it to support react@15

**Comment by hongymagic** [comment]
See: e800c74 and `react-number-input@15.0.0-rc1`
