### ISSUE TITLE
Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by csterritt** [hongymagic/react-number-input#21]
Hello,

Thanks for doing this -- when it works, it's fantastic, and a major time-saver.

However, I'm getting this problem when I've installed this in a React 15 application.

Looking [here](https://github.com/JedWatson/react-select/issues/606) it appears that this happens when you get more than one instance of React installed in your application.  Someone in that thread found out that some code they `npm install`d had its own copy of React.

I checked, and sure enough, I found `node_modules/react-number-input/node_modules/react`.  I removed that directory and the problem went away.

Thanks!

**Comment by hongymagic** [comment]
You need to make sure you install right version of the react-number-input component and also that which ever compilation you're using is not adding extra deps.

It may be caused by `main` declaration in the package which I am about to remove. Thanks for reporting this.

**Comment by hongymagic** [comment]
Currently working on a complete rewrite see branch `feature/1.5.4`. Try it again on the branch and see if its still an issue.
