### ISSUE TITLE
Input 0 is recognized as null

### ISSUE THREAD

**Issue by choyongjoon** [hongymagic/react-number-input#23]
Since 1.5.4

After I input 0, the action logger shows null
![2017-03-14 6 07 13](https://cloud.githubusercontent.com/assets/1563230/23893252/228b08c2-08e1-11e7-8604-ff878f8be067.png)

Then I click the outside of the input, the 0 disappers
![2017-03-14 6 07 23](https://cloud.githubusercontent.com/assets/1563230/23893257/24da1082-08e1-11e7-9987-923d68de47ab.png)

**Comment by hongymagic** [comment]
Fixed in 7893fcdbfb3d93dce60bf50f210caf5fd89d01d8
