### ISSUE TITLE
Could add to block entering number if the max has been reached? 

### ISSUE THREAD

**Issue by vcardins** [hongymagic/react-number-input#24]

**Comment by hongymagic** [comment]
This is actually a regression in the rewrite, I will add it back soon.

**Comment by hongymagic** [comment]
Fixed in 2375403 released in `v15.5.0`.

**Comment by vcardins** [comment]
I managed to try it here and I notice that it clears the value once out of range. What do you think about the idea of setting the max value instead so it makes explicit what max value is? Same for min. In my use case, this would be really useful, if not by default maybe through a property.
