### ISSUE TITLE
Min/max not working, can't find anything in code

### ISSUE THREAD

**Issue by lorenzos** [hongymagic/react-number-input#26]
I noticed min/max are not working. In fact, I checked code and I found no usage of min/max props? What?

**Comment by hongymagic** [comment]
Yes when I rewrote them I didn't bring them across. I will get to it soon…

**Comment by vcardins** [comment]
hi, have any idea when you'll be able to publish this fix?

**Comment by hongymagic** [comment]
Fixed in 2375403 released `v15.5.0`

**Comment by vcardins** [comment]
Thank you !!

**Comment by hongymagic** [comment]
Although I forgot to run yarn build before publishing and I am unable to do it now... I'll get it done later today

**Comment by vcardins** [comment]
I just tried and noticed that, I was about to say that :). Thanks for being pro-active !!

**Comment by vcardins** [comment]
I managed to try it here and I notice that it clears the value once out of range. What do you think about the idea to set the max value instead so it makes explicit what max value is? Same for min. In my use case, this would be really useful, if not by default maybe through a property.

**Comment by hongymagic** [comment]
In v15.5.1

**Comment by vcardins** [comment]
Thanks for the update. All works fine now !
