### ISSUE TITLE
Currently it allows entering alpha characters but maybe restricting these on a type event would be ideal

### ISSUE THREAD

**Issue by vcardins** [hongymagic/react-number-input#27]

**Comment by vcardins** [comment]
Hey, just following up whether you have plans to implement this.
Thanks !!

**Comment by hongymagic** [comment]
Not really sold on this idea; never was a big fan of typing and being restricted and not seeing any feedback.

Could provide hooks for it tho. I've stopped using this component and I'm maintaining for the sake of it atm, if you have suggestions on how hooks could solve this let me know and I could spend some time on it.
