### ISSUE TITLE
Which one is correct Default format?

### ISSUE THREAD

**Issue by blackpost38** [hongymagic/react-number-input#29]
In *read.me*, Default format is `0,0[.][00]`

```
<NumberInput
	id="price"
	type="tel"                      // optional, input[type]. Defaults to "tel" to allow non numeric characters
	onChange={this.onPriceChange}   // function (value: number | null, event: Event)
	value={this.state.price}        // normal react input binding
	placeholder="Enter price"       // all other input properties are supported
	min={0}                         // optional, set minimum allowed value
	max={100}                       // optional, set maximum allowed value
	format="0,0[.]00"               // optional, numbro.js format string. Defaults to "0,0[.][00]"
/>
```

But in source, Default format is `0,0`.

> refs: https://github.com/hongymagic/react-number-input/blob/master/index.js#L15

Which one is default format?

If `0,0[.][00]` is correct default format, I'll fix default format and send P.R.

**Comment by hongymagic** [comment]
Good find. I feel the default should support optional decimals. If you can send the PR to change the default, it would be great 👍

**Comment by blackpost38** [comment]
@hongymagic I think so. I'll change default it to `0,0[.]00` likes **README**
