### ISSUE TITLE
Formatting still allows values a-z in Safari

### ISSUE THREAD

**Issue by michaelryancaputo** [hongymagic/react-number-input#7]
I'm using Safari Version 8.0.8 (10600.8.9). Seems this is just a Safari issue, however, was hoping this component was able to fix it somehow.

**Comment by hongymagic** [comment]
Which version were you using? 

Any browser should allow you to _enter_ anything. It will just remove them if they're not numbers.

**Comment by michaelryancaputo** [comment]
I used version 1.13.
I didn't notice it behaving like that, however I have since removed it from my app since it didn't appear to work.
