### ISSUE TITLE
Request: Format while editing

### ISSUE THREAD

**Issue by dbrans** [hongymagic/react-number-input#9]
The experience of having the text switch between unformatted and formatted as you focus and blur isn't expected by most users.

**Comment by dwendo** [comment]
This was a point of conjecture actually. It raises a couple of UX issues that need to be correctly handled for this behaviour to be intuitive and unobtrusive. Adding an option to enable this may be the way to go.

**Comment by hongymagic** [comment]
I would say adding extra commas while typing is also unexpected; so if I am on `100` then append another `0` at the end, there is an apparent movement of the cursor and the text. I personally find them a little more annoying and unintuitive.

Having said that I am happy for this  requested behaviour to be enabled via a prop.

**Comment by hongymagic** [comment]
Closing as this is old. Please re-open if necessary.
